# Generated by Django 4.2.16 on 2024-11-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='utitle',
        ),
    ]
