# Generated by Django 4.2.16 on 2024-12-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_news_rename_utitle_game_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
